# Generated by Django 2.1.1 on 2019-01-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
